global using Xunit;
global using Backend.Core.Models;
global using Backend.Api.DAL;
global using System;
global using System.Collections;
global using System.Collections.Generic;
global using Backend.UnitTest.Data;
global using Backend.UnitTest.Data.Converters;
global using Backend.Core.Interfaces;