name: Unit- and Integrations-Tests

on: pull_request

jobs:
  our-automated-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The tests has started"
      - run: echo "this was run on ${{runner.os}}"
      - run: echo "started in ${{github.repository}} on ${{github.ref_name}} branch"

  build-and-test:
    runs-on: ubuntu-latest    
    
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run UnitTests
        run: dotnet test Tests/Backend.UnitTest/Backend.UnitTest.csproj --no-build
      - name: Run IntegrationTests
        run: dotnet test Tests/Backend.IntegrationTest/Backend.IntegrationTest.csproj --no-build
